---
  - name: update upconf
    local_action: git repo={{ upconf_repo }} dest={{ upconf_path }} version={{ upconf_version | default('master') }}
  - name: get conf hash
    local_action: shell cd {{ upconf_path }} && git rev-parse --short HEAD
    register: conf_hash
  - name: collect facts
    upyun_vivi:
  - name: sync main config
    synchronize: src={{ src_main_path }}/nginx/conf/ dest={{ src_main_path }}/nginx/conf/ dest_port=65422 delete=yes
  - name: sync upconf config
    synchronize: src={{ src_conf_path }}/conf/ dest={{ dest_conf_path }}/conf/ dest_port=65422
  - name: sync templeate
    template: src={{ src_conf_path }}/{{ item }} dest={{ dest_conf_path }}/{{ item }}
    with_items:
      - app/etc/config.lua
      - conf/nginx.conf
      - conf/vivi/vivi.conf
      - conf/vivi/vivi_status.conf
      - conf/vivi/upstream.conf
      - conf/vivi/access_limit.conf
