---
- hosts: "{{ node }}" 
  vars_prompt:
    - name: version
      prompt: "Input version"
      default: "NOT_BACKUP"
      private: no
  vars_files:
    - roles/cfg/shanks.yml
  roles:
    - shanks
