---
  - name: check backup dir
    shell: "[ -d {{ backup_path }} ] || mkdir {{ backup_path }} "
    when: version != "NOT_BACKUP"
  - name: backup cdn-migration
    shell: cd {{ backup_path }} ; tar -zcf cdn-migration-{{ version }}.tgz {{ live_path }}
    when: version != "NOT_BACKUP"
