---
  - name: update upconf
    local_action: git repo=ssh://gitlab@gitlab.widget-inc.com:65422/upyun-core/upconf.git
                  dest={{ upconf_path }}
                  version="{{ upconf_version| default('master') }}"
  - name: get conf hash
    local_action: shell cd {{ upconf_path }} && git rev-parse --short HEAD
    register: conf_hash
  - name: collect facts
    upyun_marco: 
  - name: synco config
    synchronize: src={{ dev_conf_path }}/nginx dest={{ live_path }} dest_port=65422
  - name: sync marco config
    synchronize: src={{ dev_conf_path }}/nginx/conf/marco dest={{ live_path }}/nginx/conf/ dest_port=65422 delete=yes
  - name: add monitor file
    shell: "[ -e {{ live_path }}/nginx/html/test.test ] || echo test >  {{ live_path }}/nginx/html/test.test"
  - name: modify by template
    template: src={{ dev_conf_path }}/{{ item }} dest={{ live_path }}/{{ item }}
    with_items:
      - nginx/app/etc/config.lua
      - nginx/conf/nginx.conf
      - nginx/conf/marco/marco.conf
      - nginx/conf/marco/upstream.conf
      - nginx/conf/marco/upyun_http.conf
      - nginx/conf/marco/upyun_https.conf
      - nginx/conf/marco/upyun_utils.conf
      - nginx/conf/marco/yupoo.conf
  - name: check nginx config
    shell: /usr/local/marco/nginx/sbin/nginx -t
