---
  - name: check backup dir
    shell: "[ -d {{ backup_path }} ] || mkdir {{ backup_path }} "
    when: version != "NOT_BACKUP"
  - name: backup shanks
    shell: cd {{ backup_path }} ; tar -zcf shanks-{{ version }}.tgz {{ live_path }}
    when: version != "NOT_BACKUP"
