---
  - name: update upconf
    local_action: git repo=ssh://gitlab@gitlab.widget-inc.com:65422/upyun-core/upconf.git
         dest={{ upconf_path }}
         version="{{ upconf_version| default('master') }}"
  - name: get conf hash
    local_action: shell cd {{ dev_conf_path }} && git rev-parse --short HEAD
    register: conf_hash
  - name: collect facts
    upyun_shanks: 
  - name: sync config
    synchronize: src={{ dev_conf_path }}/nginx dest={{ live_path }} dest_port=65422
  - name: sync shanks config
    synchronize: src={{ dev_conf_path }}/nginx/conf/shanks dest={{ live_path }}/nginx/conf/ dest_port=65422 delete=yes
  - name: modify by template
    template: src={{ dev_conf_path }}/{{ item }} dest={{ live_path }}/{{ item }}
    with_items:
      - nginx/app/etc/config.lua
      - nginx/conf/nginx.conf
      - nginx/conf/shanks/upstream.conf 
