---
  - name: sync luajit
    synchronize: src={{ dev_proc_path }}/luajit/ dest={{ live_path }}/luajit/ dest_port=65422 delete=yes
  - name: sync app
    synchronize: src={{ dev_proc_path }}/nginx/app/ dest={{ live_path }}/nginx/app/ dest_port=65422 rsync_opts="--exclude=etc/*" delete=yes
  - name: sync nginx
    synchronize: src={{ dev_proc_path }}/nginx/sbin/nginx dest={{ live_path }}/nginx/sbin/nginx dest_port=65422
  - name: sync nginx config
    synchronize: src={{ dev_proc_path }}/nginx/conf dest={{ live_path }}/nginx/ rsync_opts="--exclude=shanks/* --exclude=nginx.conf" dest_port=65422 delete=yes
